### Experiment #6 (Method Comparison)
- Script: mamdani_tsk_selection.py
- Raw data generation command:
```bash
	$ bin/methods_comparison
```
- Raw data result: Method_Comparison.xlsx
- Time required: total +/- 1 minute

In [8]:
from notebook_resolver import *
import pandas as pd
from src.utils.excel_operation import export_to_excel

file_path = "experiments/Method_Comparisons.xlsx"

df = pd.read_excel(file_path)

pivot_df = df.pivot(index="Worksheet Name", columns="Predictor Method", values="R2")

pivot_df = pivot_df[
    ["ModelMethod.TSK", "ModelMethod.IT2TSK", "ModelMethod.MLP", 
     "ModelMethod.SVR", "ModelMethod.RF", "ModelMethod.KNN"]
]

pivot_df.loc["Average"] = pivot_df.mean()
pivot_df = pivot_df.round(4)

pivot_df = pivot_df.reset_index()

export_to_excel(pivot_df, file_path, "pivot")

pivot_df

Predictor Method,Worksheet Name,ModelMethod.TSK,ModelMethod.IT2TSK,ModelMethod.MLP,ModelMethod.SVR,ModelMethod.RF,ModelMethod.KNN
0,1.Inside-Outside,0.9747,0.9750,0.9607,0.9829,0.9976,0.9899
1,10.Clod_Chuck,0.9838,0.9692,0.9596,0.9949,0.9980,0.9946
2,11.Shin,0.9829,0.9859,0.9538,0.9942,0.9974,0.9940
3,12.Fat,0.9838,0.9687,0.9464,0.9897,0.9991,0.9965
4,2.Round,0.9882,0.9905,0.9719,0.9948,0.9988,0.9955
5,3.Top_Sirloin,0.9668,0.9791,0.9529,0.9918,0.9936,0.9901
6,4.Tenderloin,0.8926,0.9884,0.9684,0.9943,0.9993,0.9978
7,5.Flap_meat,0.9866,0.9869,0.9645,0.9917,0.9978,0.9979
8,6.Striploin,0.9218,0.9920,0.9537,0.9943,0.9993,0.9970
9,7.Rib_eye,0.1608,0.9909,0.9789,0.9959,0.9977,0.9979
10,8.Skirt_meat,0.6359,0.9944,0.9747,0.9954,0.9991,0.9967
11,9.Brisket,0.9911,0.9912,0.9771,0.9950,0.9995,0.9974
12,Average,0.8724,0.9844,0.9635,0.9929,0.9981,0.9954

In [9]:
# Filter dataframe to show all IT2TSK predictor methods with R2, MSE, and MAE
it2tsk_df = df[df["Predictor Method"] == "ModelMethod.IT2TSK"].copy()

# Select relevant columns for performance analysis
it2tsk_performance = it2tsk_df[["Worksheet Name", "R2", "MSE", "MAE"]].copy()

# Round the metrics for better readability
it2tsk_performance["R2"] = it2tsk_performance["R2"].round(4)
it2tsk_performance["MSE"] = it2tsk_performance["MSE"].round(4) 
it2tsk_performance["MAE"] = it2tsk_performance["MAE"].round(4)

# Extract numeric prefix for sorting and sort by it
it2tsk_performance["Sheet_Order"] = it2tsk_performance["Worksheet Name"].str.extract(r"^(\d+)").astype(int)
it2tsk_performance = it2tsk_performance.sort_values("Sheet_Order").reset_index(drop=True)
it2tsk_performance = it2tsk_performance.drop(columns=["Sheet_Order"])  # Remove helper column

# Add average row at the bottom
avg_row = pd.DataFrame({
    "Worksheet Name": ["Average"],
    "R2": [it2tsk_performance["R2"].mean().round(4)],
    "MSE": [it2tsk_performance["MSE"].mean().round(4)],
    "MAE": [it2tsk_performance["MAE"].mean().round(4)]
})

it2tsk_performance = pd.concat([it2tsk_performance, avg_row], ignore_index=True)

export_to_excel(it2tsk_performance, file_path, "it2tsk_performance")

it2tsk_performance

      Worksheet Name      R2     MSE     MAE
0   1.Inside-Outside  0.9750  0.0021  0.0330
1            2.Round  0.9905  0.0008  0.0199
2      3.Top_Sirloin  0.9791  0.0018  0.0274
3       4.Tenderloin  0.9884  0.0010  0.0187
4        5.Flap_meat  0.9869  0.0011  0.0245
5        6.Striploin  0.9920  0.0007  0.0190
6          7.Rib_eye  0.9909  0.0008  0.0212
7       8.Skirt_meat  0.9944  0.0005  0.0140
8          9.Brisket  0.9912  0.0008  0.0183
9      10.Clod_Chuck  0.9692  0.0027  0.0299
10           11.Shin  0.9859  0.0012  0.0247
11            12.Fat  0.9687  0.0027  0.0326
12           Average  0.9844  0.0014  0.0236